### ISSUE TITLE
Xcode Error : Cannot convert value of type 'Unmanaged<CGImage>?' to specified type 'CGImage?'

### ISSUE THREAD

**Issue by vemusharan** [facebookresearch/playtorch#106]
### Version

0.2.0-rc.0

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

"dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^5.x",
    "@react-navigation/stack": "^5.x",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-pytorch-core": "0.2.0-rc.0",
    "react-native-reanimated": "^2.9.1",
    "react-native-safe-area-context": "^4.3.1",}

Xcode : Version 12.5 

When trying to build the project, Build failed with the error "Cannot convert value of type 'Unmanaged<CGImage>?' to specified type 'CGImage?' "

### Code example, screenshot, or link to repository

![Screenshot 2022-08-10 at 19 44 52](https://user-images.githubusercontent.com/70719854/183980862-5e248d62-7bc7-4d20-b31d-3563589ec806.png)

**Comment by ansonsyfang** [comment]
Hi @vemusharan, thanks for reporting the issue!

This seems to be caused by the return type change in iOS 15: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15-release-notes

* [cgImageRepresentation()](https://developer.apple.com/documentation/avfoundation/avcapturephoto/2873963-cgimagerepresentation) and [previewCGImageRepresentation()](https://developer.apple.com/documentation/avfoundation/avcapturephoto/2873945-previewcgimagerepresentation) now return CGImage? instead of Unmanaged<CGImage>? in Swift. (44734827)

You should be able to build it successfully by upgrading Xcode to 13 and using iOS 15.

We would look into a fix to support iOS 14 and below.

**Comment by vemusharan** [comment]
Thanks a lot @ansonsyfang for quick response. Yes upgrading to Xcode 13 resolved the Issue :)
